### ISSUE TITLE
Excessive lag when switching from private messages to main chat

### ISSUE THREAD

**Issue by ghost** [Cryptodog/cryptodog#48] opened 2018-10-02 21:45 UTC
Title. Web client hitches when clicking from private messages to main chat. Even on fresh connects its barely noticeable, but as chat history length increases, so does the length of the hitch. it is one way though, as moving from main to PM is smooth.

**Comment by superp00t** [comment] 2018-10-02 22:56
This is a duplicate of issue #24 .

**Comment by ayyghost** [comment] 2018-10-03 00:16
Yeah, this is a known design flaw. It's one of those things where fixing it would require more thought and effort than it's worth. I tried once and gave up because the task was too daunting.

I'm not saying _wontfix_; I may very well get around to it some day. But not right now. Though, I'm completely open to pull requests, so if you want to do the work for me, be my guest.

**Comment by superp00t** [comment] 2018-11-17 19:09
In my [binary_extensions](https://github.com/Cryptodog/cryptodog/tree/binary_extensions) branch, I have attempted to solve this problem by changing how Cryptodog stores and displays the message log. 

Previously messages were stored as an ever-expanding buffer of HTML: now the message log is an Array of objects that get re-drawed onto the conversation div whenever they change. If the number of messages in log exceeds a certain number (binary_extensions has it set to 512), old messages are deleted.

I am still unsure whether my changes are bugfree; more testing is needed before they can be merged.

**Comment by ayyghost** [comment] 2020-04-26 01:53
Should be fixed by 994a8e8a03551981a4911fced91a3af1593c69d4, but more testing is needed.

Update: fixed.

**Closed as completed** 2020-04-30 01:04 UTC
Labels: help wanted, design-flaw
